#运行模式
app:
  runMode: "debug"
  secret: "!!#$456"
  pageSize: 10
#服务运行配置
server:
  port: 8080
  readTimeOut: 60
  writeTimeOut: 60

database:
  type: "mysql"
  user: "root"
  pwd: "123456"
  url: "127.0.0.1:3306"
  name: "web"
  tablePrefix: "blog_"

runtime:
  logSavePath: "runtime/logs/"


